name: Python Setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-python:
    runs-on: fedora-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.14
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # rq.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
